### ISSUE TITLE
Paper / code parameters for reproducing experiments

### ISSUE THREAD

**Issue by engharat** [haeusser/learning_by_association#10]
Hi,
I'd like to ask few questions about code parameters, in order to reproduce exactly the experiments in the paper.
Referring to SVHN -> MNIST and SYNTH SIGNS -> GTSRB experiments:

- Both of them use svhn_model right?

-  What is the flag term associated to Delay (steps) for L_assoc ?

- sup_per_class is set by default at 100, but it should be put at -1 for using the whole dataset right?

-  Batch size is controlled by the use of unsup_batch_size for unlabeled target dataset, and sup_per_batch for the labeled source dataset, so for example to get 1032 target batch size for GTSRB(43 classes) this need to be set to 24?

Thanks in advance!

**Comment by haeusser** [comment]
Hi @engharat 

- Yes, all domain adaptation experiments were carried out with the `svhn_model`.
- It is `walker_weight_envelope_delay `.
- That is correct.
- That is correct.

Here are the hyper parameters for the experiment:
```
{
  "target_dataset": "gtsrb",
  "walker_weight_envelope_delay": "0",
  "max_checkpoints": 5,
  "dataset": "synth_signs",
  "visit_weight": "0.1",
  "tag": "da",
  "sup_per_batch": 24,
  "walker_weight_envelope_steps": 1,
  "noexec": false,
  "noeval": false,
  "eval_batch_size": 24,
  "walker_weight_envelope": "linear",
  "headless": true,
  "unsup_batch_size": 1032,
  "visit_weight_envelope": "linear",
  "checkpoint": "",
  "decay_steps": 9000,
  "logdir": "/usr/wiss/haeusser/logs/da_signs_gtsrb",
  "template": "/usr/wiss/haeusser/experiments/da_signs_gtsrb/4_da.json",
  "sup_per_class": -1,
  "max_steps": 12000,
  "finetune": "",
  "architecture": "svhn_model"
}
```

Best,
Philip
