### ISSUE TITLE
what's the data augmentation used in SVHN

### ISSUE THREAD

**Issue by yfllllll** [haeusser/learning_by_association#13]
In the paper "learning by association", the data augmentation is used in SVHN. I tried the data augmentation method described in paper, however failed to get the reported results. Can you share the data augmentation code?

**Comment by haeusser** [comment]
Hi there, sorry about the late response. 
All code is in the repository. Please have a look at [this discussion](https://github.com/haeusser/learning_by_association/issues/3) for the flags that will activate the correct augmentation scheme.
