### ISSUE TITLE
 Inquiry about experimental result

### ISSUE THREAD

**Issue by sweetdream33** [haeusser/learning_by_association#14]
Thank you for providing us with the code. 
I'm running the train.py corresponding Domain adaptation (SVHN->MNIST) 
I only modified hyper parameter (visit_weight, walker weight = 0.5, steps = 9000)
Result of eval.py looks like :
![image](https://user-images.githubusercontent.com/36881263/44316758-7cabfb80-a468-11e8-83f6-3d648cfdf8bc.png)
Accuracy of selected architecture is 97.62%. This result is lower than 99.5% (errors(%) = 0.51,  Result of paper - Table 5 ).
What's the reason? Do I have to modify parameters ( visit weight, walker weight, learning rate, steps)?

The hyper parameter settings I have run are shown below.
![image](https://user-images.githubusercontent.com/36881263/44316698-e8da2f80-a467-11e8-9ad6-29fd1a34f297.png)

**Comment by haeusser** [comment]
Well if you change the hyper parameters, the results will also change. 

Please see [this issue](https://github.com/haeusser/learning_by_association/issues/3) for a discussion of the hyper parameters. 

Cheers,
Philip
